#!/bin/bash -x

rm -rf gen/*
for v in \
    14 \
    13 \
    12 \
    11 \
    10 \
    09 \
    08 \
    07 \
    06 \
    05 \
    04 \
    03 \
    02 \
	     ;
    do
    ./DOIT 4 $v
    done

./DOIT 5 0
./DOIT 5 1
./DOIT 5 2
